
export const Packages = [
  {
    id: 1,
    title: "Hospedagem 1",
    fee: 0,
    description: "você não paga nada para usar sem taxa de setup",
    subTitle: "Ideal para quem está começando",
    location: "Estados Unidos",
    features: [
      "Servidores em nossos data center americanos",
      "ASP, ASP.NET 2.0/3.0/3.5/ e 4.0/4.5/4.5.1/4.5.2 (medium trust) ou PHP 5.3, 5.4, 5.5, 5.6 e 7.0;",
      "1 usuário de FTP para upload ou donwload;",
      "1 contas de e-mails profissionais;",
      "1 subdomínio gratuito",
    ],
    applications: {
      name: "Aplicativos disponíveis",
      features: ["Wordpress", "Drupal", "entre outros..."],
    },
    migration: null,
    pluses: {
      name: "Você ainda tem",
      features: [
        "Webmail RoundCube;",
        "AntiSpam;",
        "Painel de controle web;",
        "Painel de gerencamento de DNS;",
        "Configurações de PHP personalizáveis;",
        "Certificado SSL Grátis;",
        "Transferência ilimitada.",
      ],
    },
    mostWanted: 0,
  },
  {
    id: 2,
    title: "Hospedagem 2",
    fee: 499,
    description: "cobrado mensalmente sem taxa de setup",
    subTitle: "Ideal para site com mais de 30k de visitas.",
    location: "Brasil",
    features: [
      "Servidores em São Paulo",
      "ASP, ASP.NET 2.0/3.0/3.5/ e 4.0/4.5/4.5.1/4.5.2 (medium trust) ou PHP 5.3, 5.4, 5.5, 5.6 e 7.0;",
      "10 usuários de FTP para upload ou donwload;",
      "30 contas de e-mails profissionais;",
      "10 subdomínio gratuito",
    ],
    applications: {
      name: "Aplicativos disponíveis",
      features: ["Wordpress", "Drupal", "entre outros..."],
    },
    migration: {
      name: "Migração Gratuita",
      sub: "Migramos todos seus sites para nossos servidores;",
    },
    pluses: {
      name: "Você ainda tem",
      features: [
        "Webmail RoundCube;",
        "AntiSpam;",
        "Painel de controle web;",
        "Painel de gerencamento de DNS;",
        "Configurações de PHP personalizáveis;",
        "Certificado SSL Grátis;",
        "Transferência ilimitada.",
      ],
    },
    mostWanted: 1,
  },
  {
    id: 3,
    title: "Hospedagem 3",
    fee: 999,
    description: "cobrado mensalmente sem taxa de setup",
    subTitle: "Ideal para site com mais de 60k de visitas",
    location: "Brasil",
    features: [
      "Servidores em São Paulo",
      "ASP, ASP.NET 2.0/3.0/3.5/ e 4.0/4.5/4.5.1/4.5.2 (medium trust) ou PHP 5.3, 5.4, 5.5, 5.6 e 7.0;",
      "ilimitados usuários de FTP para upload ou donwload;",
      "ilimitadas de e-mails profissionais;",
      "50 subdomínio gratuito",
    ],
    applications: {
      name: "Aplicativos disponíveis",
      features: ["Wordpress", "Drupal", "entre outros..."],
    },
    migration: {
      name: "Migração Gratuita",
      sub: "Migramos todos seus sites para nossos servidores;",
    },
    pluses: {
      name: "Você ainda tem",
      features: [
        "Webmail RoundCube;",
        "AntiSpam;",
        "Painel de controle web;",
        "Painel de gerencamento de DNS;",
        "Configurações de PHP personalizáveis;",
        "Certificado SSL Grátis;",
        "Transferência ilimitada.",
      ],
    },
    mostWanted: 0,
  },
];
